package-lock.json
package.json
src/App.vue
src/main.js
src/router.js
src/views/Login.vue
tailwind.config.js

Close VOL-15
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/aTEJMezpTFeod3w8Z2C6Lg?src=GitHub) by JessiIglesias on Jan 11, 2023
[VOL-15 Generar login de acceso](https://ducter-development.atlassian.net/browse/VOL-15)  

Vista para Login de usuario

---

package-lock.json
package.json
src/components/Forms/FormGenerarPassword.vue
src/components/Forms/FormLogin.vue
src/components/Forms/FormRecuperarPassword.vue
src/components/HelloWorld.vue
src/config/index.js
src/modules/auth/composables/auth.js
src/modules/auth/store/login.js
src/router.js
src/views/Login.vue
src/views/RecuperarPassword.vue

Close VOL-16
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/008zdnZAQlOywhoRt6mw2A?src=GitHub) by JessiIglesias on Jan 12, 2023
[VOL-16 Generar recuperar contraseña](https://ducter-development.atlassian.net/browse/VOL-16)  

Añadir front para recuperar contraseña

---

src/layout/components/Header/Index.vue
src/layout/components/Sidebar/Index.vue
src/layout/components/Sidebar/Secondary.vue
src/modules/archivos/router/index.js
src/modules/archivos/views/Home.vue
src/modules/auth/composables/useAuth.js
src/modules/auth/router/index.js
src/modules/auth/store/login.js
src/modules/dashboard/layouts/DashboardLayout.vue
src/modules/dashboard/router/index.js
src/modules/densidades/router/index.js
src/modules/densidades/views/Home.vue
src/modules/dictamenes/router/index.js
src/modules/dictamenes/views/Home.vue
src/modules/errores/router/index.js
src/modules/errores/views/Home.vue
src/router.js
src/views/Landing.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/yEJ9jFxXSvikMimTeL2C-w?src=GitHub) by ducter-dev on Jul 6, 2023
[VD-31 Creación Sidebar](https://ducter-development.atlassian.net/browse/VD-31)  

VD-31 Creación Sidebar

---

src/layout/components/Modal/Index.vue
src/layout/components/Paginate/Index.vue
src/modules/balances/store/balanceStore.js
src/modules/clientes/composables/cliente.js
src/modules/clientes/store/clienteStore.js
src/modules/dashboard/views/Dashboard.vue
src/modules/dictamenes/components/FormDictamen.vue
src/modules/dictamenes/components/Paginate.vue
src/modules/dictamenes/composables/dictamen.js
src/modules/dictamenes/router/index.js
src/modules/dictamenes/store/dictamenStore.js
src/modules/dictamenes/views/Create.vue
src/modules/dictamenes/views/Delete.vue
src/modules/dictamenes/views/Edit.vue
src/modules/dictamenes/views/Home.vue
tailwind.config.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/w7lf73ZXTFOjhMmIE7SxVA?src=GitHub) by ducter-dev on Jul 7, 2023
[VD-32 Crud Dictámenes](https://ducter-development.atlassian.net/browse/VD-32)  

VD-32 Crud Dictámenes

---

src/layout/components/Paginate/Index.vue
src/modules/densidades/components/FormDensidad.vue
src/modules/densidades/composables/densidades.js
src/modules/densidades/router/index.js
src/modules/densidades/store/densidadStore.js
src/modules/densidades/views/Create.vue
src/modules/densidades/views/Delete.vue
src/modules/densidades/views/Edit.vue
src/modules/densidades/views/Home.vue
src/modules/dictamenes/components/FormDictamen.vue
src/modules/dictamenes/store/dictamenStore.js
src/modules/dictamenes/views/Edit.vue
src/modules/dictamenes/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/dMhs6GBORJ2dyk0DsGzzdQ?src=GitHub) by ducter-dev on Jul 7, 2023
[VD-33 Crud Densidades](https://ducter-development.atlassian.net/browse/VD-33)  

VD-33 Creado Crud de Densidades

---

src/modules/archivos/views/Home.vue
src/modules/errores/composables/useErrores.js
src/modules/errores/store/erroresStore.js
src/modules/errores/views/Home.vue
src/router.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/nlTWvEQcSEOJpipx1WKGTw?src=GitHub) by ducter-dev on Jul 17, 2023
[VD-35 Sección Errores](https://ducter-development.atlassian.net/browse/VD-35)  

VD-35 Creada sección erroresz

---

src/modules/densidades/views/Delete.vue
src/modules/densidades/views/Edit.vue
src/modules/perfiles/components/FormPerfiles.vue
src/modules/perfiles/composables/index.js
src/modules/perfiles/store/perfilesStore.js
src/modules/perfiles/views/Create.vue
src/modules/perfiles/views/Delete.vue
src/modules/perfiles/views/Edit.vue
src/modules/perfiles/views/Home.vue
src/modules/permisos/composables/index.js
src/modules/permisos/store/permisoStore.js
src/modules/usuarios/views/Delete.vue
src/modules/usuarios/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/o-659xWdTOmqBSlfeKYTRg?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-38 Crud Perfiles](https://ducter-development.atlassian.net/browse/VD-38)  

vd-38 Terminado CRUD Perfiles

---

src/modules/perfiles/views/Edit.vue
src/modules/permisos/components/FormPermiso.vue
src/modules/permisos/store/permisoStore.js
src/modules/permisos/views/Create.vue
src/modules/permisos/views/Delete.vue
src/modules/permisos/views/Edit.vue
src/modules/permisos/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/1wA2OvYFQgO19MF52seeng?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-39 Crud Permisos](https://ducter-development.atlassian.net/browse/VD-39)  

VD-39 Crud Permisos

---

src/modules/clientes/components/FormClientes.vue
src/modules/clientes/composables/cliente.js
src/modules/clientes/store/clienteStore.js
src/modules/clientes/views/Create.vue
src/modules/clientes/views/Delete.vue
src/modules/clientes/views/Edit.vue
src/modules/clientes/views/Home.vue
src/modules/perfiles/views/Create.vue
src/modules/perfiles/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/THX_gRuiQUCWPK_9wueCgg?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-41 Crud Clientes](https://ducter-development.atlassian.net/browse/VD-41)  

VD-41 Crud Clientes

---

src/modules/eventos/components/FormEventos.vue
src/modules/eventos/composables/evento.js
src/modules/eventos/store/eventoStore.js
src/modules/eventos/views/Create.vue
src/modules/eventos/views/Delete.vue
src/modules/eventos/views/Edit.vue
src/modules/eventos/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/P1OnEv47R_q2EhHFbkuJ3A?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-47 Crud Eventos](https://ducter-development.atlassian.net/browse/VD-47)  

VD-47 Crud Eventos

---

src/modules/bitacora/composables/index.js
src/modules/bitacora/store/bitacora.js
src/modules/bitacora/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/0DSrnk_FSJ2jwpqkWoUv1w?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-46 Crud Bitácora](https://ducter-development.atlassian.net/browse/VD-46)  

VD-46 Crud Bitácora

---

src/modules/compuestos/components/FormCompuestos.vue
src/modules/compuestos/composables/compuestos.js
src/modules/compuestos/store/compuestosStore.js
src/modules/compuestos/views/Create.vue
src/modules/compuestos/views/Delete.vue
src/modules/compuestos/views/Edit.vue
src/modules/compuestos/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/4QsE0TL_QfaQwU39cDQnkQ?src=GitHub) by ducter-dev on Jul 21, 2023
[VD-45 Crud Compuesto](https://ducter-development.atlassian.net/browse/VD-45)  

VD-45 Crud Compuesto

---

src/assets/icons/eyes.svg
src/layout/components.js
src/layout/components/Form/TextPlane.vue
src/modules/empresas/components/FormEmpresas.vue
src/modules/empresas/composables/empresa.js
src/modules/empresas/routes/index.js
src/modules/empresas/store/empresaStore.js
src/modules/empresas/views/Edit.vue
src/modules/empresas/views/Home.vue
src/modules/empresas/views/Show.vue
src/modules/productos/composables/productos.js
src/modules/productos/store/productoStore.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/iok03P29QQueu1hN0G30Fg?src=GitHub) by ducter-dev on Jul 24, 2023
[VD-40 Crud Empresas](https://ducter-development.atlassian.net/browse/VD-40)  

VD-40 Crud Empresas

---

src/modules/revisiones/components/FormRevision.vue
src/modules/revisiones/composables/index.js
src/modules/revisiones/store/revisionStore.js
src/modules/revisiones/views/Delete.vue
src/modules/revisiones/views/Edit.vue
src/modules/revisiones/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/Lm0LfwzxR8iCoCI4utK42A?src=GitHub) by ducter-dev on Jul 24, 2023
[VD-48 Crud Revisión](https://ducter-development.atlassian.net/browse/VD-48)  

VD-48 Crud Revisión

---

src/modules/compuestos/composables/compuestos.js
src/modules/compuestos/store/compuestosStore.js
src/modules/productos/components/FormProductos.vue
src/modules/productos/composables/productos.js
src/modules/productos/store/productoStore.js
src/modules/productos/views/Create.vue
src/modules/productos/views/Delete.vue
src/modules/productos/views/Edit.vue
src/modules/productos/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/htXf-88tT1eJsknmvSGN3w?src=GitHub) by ducter-dev on Jul 31, 2023
[VD-44 Crud Producto](https://ducter-development.atlassian.net/browse/VD-44)  

VD-44 Crud Producto

---

src/modules/perfiles/composables/index.js
src/modules/perfiles/store/perfilesStore.js
src/modules/usuarios/views/Home.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/R5jDCj79RCOctAdhFmZGjw?src=GitHub) by ducter-dev on Jul 31, 2023
[VD-50 Registrar usuario enviar credenciales](https://ducter-development.atlassian.net/browse/VD-50)  

VD-50 Registrar usuario enviar credenciales

---

src/modules/auth/store/login.js
src/modules/auth/views/Login.vue
src/modules/auth/views/RescutePassword.vue
src/modules/auth/views/ResetPassword.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/lVnmoFmPQMaBPX3LEoAVdg?src=GitHub) by ducter-dev on Aug 1, 2023
[VD-51 Activar cuenta](https://ducter-development.atlassian.net/browse/VD-51)  

VD-51 Activar cuenta

---

src/modules/auth/store/login.js
src/modules/auth/views/Login.vue
src/modules/auth/views/RescutePassword.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/bt4eQTG4Tgm7xjqN1--c6Q?src=GitHub) by ducter-dev on Aug 10, 2023
[VD-58 Crear formulario para solicitar nuevas credenciales](https://ducter-development.atlassian.net/browse/VD-58)  

VD-58 Crear formulario para solicitar nuevas credenciales

---

src/modules/auth/store/login.js
src/modules/auth/views/Login.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/30-GRtsoRmCOKLaqylRCHg?src=GitHub) by ducter-dev on Aug 11, 2023
[VD-60 Mostrar mensaje de caducidad de password y enviar a formulario para actualizar password](https://ducter-development.atlassian.net/browse/VD-60)  

VD-60 Mostrar mensaje de caducidad de password y enviar a formulario para actualizar password

---

src/modules/auth/composables/useAuth.js
src/modules/auth/store/login.js
src/modules/auth/views/Login.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/5baY8KsiQIeOLtUn872fuw?src=GitHub) by ducter-dev on Aug 11, 2023
[VD-63 Validar que el usuario está bloqueado y retornar la hora de desbloqueo](https://ducter-development.atlassian.net/browse/VD-63)  

Vd 62-mostrar-fecha-hora-de-desbloqueo-en-el-front

---

src/layout/session/Index.vue
src/modules/auth/views/Login.vue
src/modules/dashboard/layouts/DashboardLayout.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/S-szz3LmR_S7fmlaVaJu0A?src=GitHub) by ducter-dev on Aug 11, 2023
[VD-55 Cerrar sesión inactiva](https://ducter-development.atlassian.net/browse/VD-55)  

VD-55 Cerrar sesión inactiva

---

src/modules/auth/composables/useAuth.js
src/modules/auth/store/login.js
src/modules/auth/views/ResetPassword.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/_1wF_DMqRP-yX8s0voObQQ?src=GitHub) by ducter-dev on Aug 15, 2023
[VD-66 Crear funcionalidad para envío de nueva contraseña (frontend)](https://ducter-development.atlassian.net/browse/VD-66)  

VD-66 Crear funcionalidad para envío de nueva contraseña (frontend)
